// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzcuwbzyxgrmkqejtshy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6Y3V3Ynp5eGdybWtxZWp0c2h5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NjUzNDksImV4cCI6MjA3NDE0MTM0OX0.PysFyk66aGRsOTEGjFH7DhK83Hf1UrFypGQWVdKLsJ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});